const products = [
  {
    id: 1,
    name: "Embroidered Silk Kurta",
    price: 4999,
    originalPrice: 6999,
    image: "/product1.webp",
    category: "Kurtas",
    isNew: true,
  },
  {
    id: 2,
    name: "Designer Lehenga Set",
    price: 12999,
    originalPrice: 15999,
    image: "/product2.webp",
    category: "Lehengas",
    isNew: false,
  },
  {
    id: 3,
    name: "Fusion Maxi Dress",
    price: 3999,
    originalPrice: 5999,
    image: "/product3.webp",
    category: "Dresses",
    isNew: true,
  },
  {
    id: 4,
    name: "Banarasi Silk Saree",
    price: 8999,
    originalPrice: 11999,
    image: "/product4.webp",
    category: "Sarees",
    isNew: false,
  },
  {
    id: 5,
    name: "Printed Co-ord Set",
    price: 2999,
    originalPrice: 3999,
    image: "/product5.webp",
    category: "Co-ords",
    isNew: true,
  },
  {
    id: 6,
    name: "Embellished Anarkali",
    price: 7999,
    originalPrice: 9999,
    image: "/product6.webp",
    category: "Anarkalis",
    isNew: false,
  },
];
