import localFont from "next/font/local";
import "./globals.css";

import SearchOverlay from "@/components/SearchOverlay";
import CartDrawer from "@/components/CartDrawer";
import { Suspense } from "react";
import Header from "@/components/navbar";
import Footer from "@/components/footer";
import { ShopProvider } from "@/context/ShopContext";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geistMono.className}>
        <ShopProvider>
          <Suspense>
            <SearchOverlay />
            <CartDrawer />
          </Suspense>
          <Header/>
          {children}
          <Footer />
        </ShopProvider>
      </body>
    </html>
  );
}
